# 1 /  Collecte et compréhension des données

In [45]:
import pandas as pd

In [46]:
# Extraire les données à partir du csv sans affichage 
df=pd.read_csv('imdb (1000 movies) in june 2022.csv')

In [47]:
# Afficher la 10 premières lignes
df.head(10)

,ranking of movie\r\n,movie name\r\n,Year,certificate,runtime,genre,RATING,metascore,DETAIL ABOUT MOVIE\r\n,DIRECTOR\r\n,ACTOR 1\r\n,ACTOR 2\r\n,ACTOR 3,ACTOR 4,votes,GROSS COLLECTION\r\n
0,1,The Shawshank Redemption,-1994,15,142 min,Drama,9.3,81.0,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,"2,603,314",$28.34M
1,2,The Godfather,-1972,X,175 min,"Crime, Drama",9.2,100.0,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,"1,798,731",$134.97M
2,3,The Dark Knight,-2008,12A,152 min,"Action, Crime, Drama",9.0,84.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,"2,574,810",$534.86M
3,4,The Lord of the Rings: The Return of the King,-2003,12A,201 min,"Action, Adventure, Drama",9.0,94.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,"1,787,701",$377.85M
4,5,Schindler's List,-1993,15,195 min,"Biography, Drama, History",9.0,94.0,"In German-occupied Poland during World War II,...",Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,"1,323,776",$96.90M
5,6,The Godfather Part II,-1974,X,202 min,"Crime, Drama",9.0,90.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,"1,239,027",$57.30M
6,7,12 Angry Men,-1957,U,96 min,"Crime, Drama",9.0,96.0,The jury in a New York City murder trial is fr...,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,"769,113",$4.36M
7,8,Jai Bhim,-2021,All,164 min,"Crime, Drama, Mystery",8.9,NaN,When a tribal man is arrested for a case of al...,T.J. Gnanavel,Suriya,Lijo Mol Jose,Manikandan K.,Rajisha Vijayan,"191,329",NaN
8,9,Pulp Fiction,-1994,18,154 min,"Crime, Drama",8.9,94.0,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,"1,995,346",$107.93M
9,10,Inception,-2010,12A,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,A thief who steals corporate secrets through t...,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,"2,284,252",$292.58M

In [48]:
# Taille du dataset
df.shape

(1000, 16)

In [49]:
# Variables disponibles
df.columns

Index(['ranking of movie\r\n', 'movie name\r\n', 'Year', 'certificate',
       'runtime', 'genre', 'RATING', 'metascore', 'DETAIL ABOUT MOVIE\r\n',
       'DIRECTOR\r\n', 'ACTOR 1\r\n', 'ACTOR 2\r\n', 'ACTOR 3', 'ACTOR 4',
       'votes', 'GROSS COLLECTION\r\n'],
      dtype='object')

In [50]:
# Types de données
df.dtypes

ranking of movie\r\n       object
movie name\r\n             object
Year                       object
certificate                object
runtime                    object
genre                      object
RATING                    float64
metascore                 float64
DETAIL ABOUT MOVIE\r\n     object
DIRECTOR\r\n               object
ACTOR 1\r\n                object
ACTOR 2\r\n                object
ACTOR 3                    object
ACTOR 4                    object
votes                      object
GROSS COLLECTION\r\n       object
dtype: object

# 2 / Préparation des données

In [51]:
# Valeur manquantes
df.isnull()

,ranking of movie\r\n,movie name\r\n,Year,certificate,runtime,genre,RATING,metascore,DETAIL ABOUT MOVIE\r\n,DIRECTOR\r\n,ACTOR 1\r\n,ACTOR 2\r\n,ACTOR 3,ACTOR 4,votes,GROSS COLLECTION\r\n
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [52]:
# le nombre de valeurs maquantes 
df.isnull().sum()

ranking of movie\r\n        0
movie name\r\n              0
Year                        0
certificate                 5
runtime                     0
genre                       0
RATING                      0
metascore                 163
DETAIL ABOUT MOVIE\r\n      0
DIRECTOR\r\n                0
ACTOR 1\r\n                 0
ACTOR 2\r\n                 0
ACTOR 3                     0
ACTOR 4                     0
votes                       0
GROSS COLLECTION\r\n      180
dtype: int64

In [53]:
# Effacer les colonnes inutiles
df.drop(columns=['certificate'], inplace=True)

In [54]:
df.columns = df.columns.str.strip()

In [55]:
# Eliminer les colonnes inutiles
df = df.drop(columns=['ranking of movie'])

In [56]:
df.columns

Index(['movie name', 'Year', 'runtime', 'genre', 'RATING', 'metascore',
       'DETAIL ABOUT MOVIE', 'DIRECTOR', 'ACTOR 1', 'ACTOR 2', 'ACTOR 3',
       'ACTOR 4', 'votes', 'GROSS COLLECTION'],
      dtype='object')

In [57]:
# Remplacer les valeurs manquantes par la  moyenne
df['metascore'] = df['metascore'].fillna(df['metascore'].mean())

In [58]:
# Nettoyer la colonne des symboles 
df['GROSS COLLECTION'] = df['GROSS COLLECTION'].str.replace('$', '', regex=False)
df['GROSS COLLECTION'] = df['GROSS COLLECTION'].str.replace('M', '', regex=False)

In [59]:
# Convertir en numérique 
df['GROSS COLLECTION'] = pd.to_numeric(df['GROSS COLLECTION'], errors='coerce')

In [60]:
# Remplacer les valeurs manquantes par la  médianne
df['GROSS COLLECTION'] = df['GROSS COLLECTION'].fillna(df['GROSS COLLECTION'].median())

In [61]:
# Vérification 
df.isnull().sum()

movie name            0
Year                  0
runtime               0
genre                 0
RATING                0
metascore             0
DETAIL ABOUT MOVIE    0
DIRECTOR              0
ACTOR 1               0
ACTOR 2               0
ACTOR 3               0
ACTOR 4               0
votes                 0
GROSS COLLECTION      0
dtype: int64

In [62]:
# les valeurs dupliquée
df.duplicated().sum()

np.int64(0)

In [63]:
# Renommer les Variables 
df = df.rename(columns={
    'movie name': 'Title',
    'Year': 'Released Year',
    'runtime': 'Duration Min',
    'genre': 'Genre',
    'RATING': 'IMDB_Rating',
    'metascore': 'Meta Score',
    'DIRECTOR': 'Director',
    'ACTOR 1': 'Main Actor 1',
    'ACTOR 2': 'Main Actor 2',
    'ACTOR 3': 'Main Actor 3',
    'ACTOR 4': 'Main Actor 4',
    'votes': 'Num_Vote',
    'GROSS COLLECTION': 'Revenue',
    'DETAIL ABOUT MOVIE':'Movie_Details'
})

In [64]:
df.columns

Index(['Title', 'Released Year', 'Duration Min', 'Genre', 'IMDB_Rating',
       'Meta Score', 'Movie_Details', 'Director', 'Main Actor 1',
       'Main Actor 2', 'Main Actor 3', 'Main Actor 4', 'Num_Vote', 'Revenue'],
      dtype='object')

In [65]:
# Nettoyer et convertir une colonne to  numeric 
df['Num_Vote'] = df['Num_Vote'].str.replace(',', '')
df['Num_Vote'] = pd.to_numeric(df['Num_Vote'], errors='coerce')

In [66]:
df.dtypes

Title             object
Released Year     object
Duration Min      object
Genre             object
IMDB_Rating      float64
Meta Score       float64
Movie_Details     object
Director          object
Main Actor 1      object
Main Actor 2      object
Main Actor 3      object
Main Actor 4      object
Num_Vote           int64
Revenue          float64
dtype: object

In [67]:
# Convertir en numérique 
df['Released Year'] = (
    pd.to_numeric(df['Released Year'], errors='coerce')
    .abs()
    .astype('Int64')
)

In [68]:
df.dtypes

Title             object
Released Year      Int64
Duration Min      object
Genre             object
IMDB_Rating      float64
Meta Score       float64
Movie_Details     object
Director          object
Main Actor 1      object
Main Actor 2      object
Main Actor 3      object
Main Actor 4      object
Num_Vote           int64
Revenue          float64
dtype: object

In [69]:
# Nettoyer la colonne puis  Convertir en numérique 
df['Duration Min'] = df['Duration Min'].str.replace('min', '')
df['Duration Min'] = pd.to_numeric(df['Duration Min'], errors='coerce')

In [70]:
df.dtypes

Title             object
Released Year      Int64
Duration Min       int64
Genre             object
IMDB_Rating      float64
Meta Score       float64
Movie_Details     object
Director          object
Main Actor 1      object
Main Actor 2      object
Main Actor 3      object
Main Actor 4      object
Num_Vote           int64
Revenue          float64
dtype: object

# 3 / Statistiques Descriptives

In [71]:
# Statistiques descriptives des variables numériques  
df.describe()

,Released Year,Duration Min,IMDB_Rating,Meta Score,Num_Vote,Revenue
count,967.0,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000
mean,1990.4788,123.637000,7.960200,78.629630,3.025326e+05,61.836550
std,23.936236,28.559602,0.276717,11.022826,3.610305e+05,104.417052
min,1920.0,45.000000,7.600000,28.000000,2.527700e+04,0.000000
25%,1974.0,103.000000,7.700000,73.000000,6.000175e+04,5.017500
50%,1998.0,120.000000,7.900000,78.629630,1.549115e+05,23.900000
75%,2009.0,138.000000,8.100000,86.000000,4.187058e+05,63.630000
max,2022.0,321.000000,9.300000,100.000000,2.603314e+06,936.660000

In [72]:
# Statistiques descriptives des variables catégorielles
df.describe(include='object')

,Title,Genre,Movie_Details,Director,Main Actor 1,Main Actor 2,Main Actor 3,Main Actor 4
count,1000,1000,1000,1000,1000,1000,1000,1000
unique,997,202,1000,554,661,836,896,934
top,Drishyam,Drama,Two imprisoned men bond over a number of years...,Alfred Hitchcock,Tom Hanks,Emma Watson,Jennifer Connelly,Michael Caine
freq,2,84,1,13,12,6,4,4

In [73]:
#Comment évolue le nombre de films par année ? 
df['Released Year'].value_counts().sort_index()

Released Year
1920     1
1921     1
1922     1
1924     1
1925     2
        ..
2018    19
2019    24
2020     7
2021    10
2022     5
Name: count, Length: 101, dtype: Int64

# 4/ Analyse des KPI

In [74]:
#Films récents mieux notés ?
df.groupby('Released Year')['IMDB_Rating'].mean()

Released Year
1920    8.000000
1921    8.300000
1922    7.900000
1924    8.200000
1925    8.100000
          ...
2018    7.994737
2019    8.004167
2020    8.100000
2021    8.200000
2022    8.280000
Name: IMDB_Rating, Length: 101, dtype: float64

In [75]:
#Décennie la plus rentable
df['Decade'] = (df['Released Year']//10)*10
df.groupby('Decade')['Revenue'].sum()

Decade
1920       86.46
1930      691.74
1940      572.47
1950     1036.49
1960     2133.94
1970     3269.78
1980     5120.86
1990     8678.18
2000    15309.19
2010    20925.74
2020     1414.88
Name: Revenue, dtype: float64

In [76]:
#Moyenne des notes IMDB par genre
df.groupby('Genre')['IMDB_Rating'].mean()

Genre
Action, Adventure               8.300000
Action, Adventure, Biography    7.800000
Action, Adventure, Comedy       7.954545
Action, Adventure, Crime        7.600000
Action, Adventure, Drama        8.140000
                                  ...
Mystery, Romance, Thriller      8.300000
Mystery, Sci-Fi, Thriller       8.000000
Mystery, Thriller               8.100000
Thriller                        7.700000
Western                         8.125000
Name: IMDB_Rating, Length: 202, dtype: float64

In [77]:
#Top 10 des genres par revenu total
df.groupby('Genre')['Revenue'].sum().sort_values(ascending=False).head(10)

Genre
Action, Adventure, Sci-Fi       5838.93
Animation, Adventure, Comedy    5458.08
Action, Adventure, Fantasy      3197.18
Action, Adventure, Drama        2982.60
Animation, Action, Adventure    2329.67
Drama                           2116.66
Drama, Romance                  1987.08
Action, Adventure, Comedy       1968.21
Action, Crime, Drama            1731.22
Crime, Drama, Thriller          1293.30
Name: Revenue, dtype: float64

In [78]:
#Top 10 des réalisateurs par note moyenne
df.groupby('Director')['IMDB_Rating'].mean().sort_values(ascending=False).head(10)

Director
Frank Darabont        8.95
T.J. Gnanavel         8.90
Irvin Kershner        8.70
Sudha Kongara         8.70
Lana Wachowski        8.70
Masaki Kobayashi      8.60
Joseph Kosinski       8.60
Roberto Benigni       8.60
Fernando Meirelles    8.60
Milos Forman          8.55
Name: IMDB_Rating, dtype: float64

In [79]:
#Top 10 des acteurs principaux par revenu total
df.groupby('Main Actor 1')['Revenue'].sum().sort_values(ascending=False).head(10)

Main Actor 1
Tom Hanks            2493.08
Joe Russo            2205.04
Leonardo DiCaprio    1877.33
Daniel Radcliffe     1533.94
Christian Bale       1351.59
Elijah Wood          1035.94
Robert Downey Jr.     941.69
Daisy Ridley          936.66
Mark Hamill           922.35
Craig T. Nelson       870.02
Name: Revenue, dtype: float64

In [80]:
df.groupby('Main Actor 2')['Revenue'].sum().sort_values(ascending=False).head(10)

Main Actor 2
Robert Downey Jr.    1570.27
Chris Evans          1456.49
Emma Watson          1342.20
Ian McKellen         1195.01
Zoe Saldana          1150.32
Tim Allen            1040.84
John Boyega           936.66
Harrison Ford         922.35
Zendaya               804.75
Kate Winslet          788.59
Name: Revenue, dtype: float64

In [81]:
df.groupby('Main Actor 3')['Revenue'].sum().sort_values(ascending=False).head(10)

Main Actor 3
Rupert Grint            1216.36
Carrie Fisher           1015.17
Sigourney Weaver         999.14
Oscar Isaac              962.10
Chris Evans              858.37
Benedict Cumberbatch     804.75
Scarlett Johansson       702.29
Chris Hemsworth          678.82
Billy Zane               659.33
Orlando Bloom            620.95
Name: Revenue, dtype: float64

In [82]:
df.groupby('Main Actor 4')['Revenue'].sum().sort_values(ascending=False).head(10)

Main Actor 4
Mark Ruffalo          1852.25
Domhnall Gleeson      1120.30
Jacob Batalon          804.75
Michelle Rodriguez     760.51
Michael Caine          751.76
Orlando Bloom          720.40
Scarlett Johansson     667.85
Kathy Bates            659.33
Jeremy Renner          623.28
Huck Milner            608.58
Name: Revenue, dtype: float64

In [83]:
#Top 10 des genres ayant la plus longue durée moyenne
df.groupby('Genre')['Duration Min'].mean().sort_values(ascending=False).head(10)

Genre
Drama, Musical, Sport        224.000000
Adventure, Drama, Family     220.000000
Crime, Drama, Fantasy        189.000000
Drama, Family, Musical       181.000000
Biography, Comedy, Crime     180.000000
Adventure, Drama, History    174.666667
Biography, Drama, War        172.000000
Comedy, Drama, Musical       170.500000
Adventure, Drama, War        166.333333
Drama, Musical               166.000000
Name: Duration Min, dtype: float64

In [84]:
#Filtrer les films ayant une note superieure à 8
df[df['IMDB_Rating'] > 8]

,Title,Released Year,Duration Min,Genre,IMDB_Rating,Meta Score,Movie_Details,Director,Main Actor 1,Main Actor 2,Main Actor 3,Main Actor 4,Num_Vote,Revenue,Decade
0,The Shawshank Redemption,1994,142,Drama,9.3,81.00000,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2603314,28.34,1990
1,The Godfather,1972,175,"Crime, Drama",9.2,100.00000,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1798731,134.97,1970
2,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,84.00000,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2574810,534.86,2000
3,The Lord of the Rings: The Return of the King,2003,201,"Action, Adventure, Drama",9.0,94.00000,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1787701,377.85,2000
4,Schindler's List,1993,195,"Biography, Drama, History",9.0,94.00000,"In German-occupied Poland during World War II,...",Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1323776,96.90,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,La Grande Illusion,1937,113,"Drama, War",8.1,78.62963,"During WWI, two French soldiers are captured a...",Jean Renoir,Jean Gabin,Dita Parlo,Pierre Fresnay,Erich von Stroheim,36438,0.17,1930
328,It Happened One Night,1934,105,"Comedy, Romance",8.1,87.00000,A renegade reporter trailing a young runaway h...,Frank Capra,Clark Gable,Claudette Colbert,Walter Connolly,Roscoe Karns,102808,4.36,1930
329,All Quiet on the Western Front,1930,152,"Drama, War",8.1,91.00000,"A German youth eagerly enters World War I, but...",Lewis Milestone,Lew Ayres,Louis Wolheim,John Wray,Arnold Lucy,61054,3.27,1930
330,The Circus,1928,72,"Comedy, Family, Romance",8.1,90.00000,The Tramp finds work and the girl of his dream...,Charles Chaplin,Charles Chaplin,Merna Kennedy,Al Ernest Garcia,Harry Crocker,33479,23.90,1920
331,Sunrise: A Song of Two Humans,1927,94,"Drama, Romance",8.1,78.62963,A sophisticated urban woman seduces a farmer i...,F.W. Murnau,George O'Brien,Janet Gaynor,Margaret Livingston,Bodil Rosing,50745,0.54,1920

In [85]:
#Filtrer les films avec un revenu superieur à 100
df[df['Revenue'] > 100]

,Title,Released Year,Duration Min,Genre,IMDB_Rating,Meta Score,Movie_Details,Director,Main Actor 1,Main Actor 2,Main Actor 3,Main Actor 4,Num_Vote,Revenue,Decade
1,The Godfather,1972,175,"Crime, Drama",9.2,100.0,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1798731,134.97,1970
2,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,84.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2574810,534.86,2000
3,The Lord of the Rings: The Return of the King,2003,201,"Action, Adventure, Drama",9.0,94.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1787701,377.85,2000
8,Pulp Fiction,1994,154,"Crime, Drama",8.9,94.0,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1995346,107.93,1990
9,Inception,2010,148,"Action, Adventure, Sci-Fi",8.8,74.0,A thief who steals corporate secrets through t...,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2284252,292.58,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,Die Hard: With a Vengeance,1995,128,"Action, Adventure, Thriller",7.6,58.0,John McClane and a Harlem store owner are targ...,John McTiernan,Bruce Willis,Jeremy Irons,Samuel L. Jackson,Graham Greene,383647,100.01,1990
976,The Little Mermaid,1989,83,"Animation, Adventure, Comedy",7.6,88.0,A mermaid princess makes a Faustian bargain in...,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,257483,111.54,1980
983,Close Encounters of the Third Kind,1977,138,"Drama, Sci-Fi",7.6,90.0,"Roy Neary, an Indiana electric lineman, finds ...",Steven Spielberg,Richard Dreyfuss,François Truffaut,Teri Garr,Melinda Dillon,199164,132.09,1970
988,The Jungle Book,1967,78,"Animation, Adventure, Comedy",7.6,65.0,Bagheera the Panther and Baloo the Bear have a...,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,179851,141.84,1960
997,Snow White and the Seven Dwarfs,1937,83,"Animation, Adventure, Family",7.6,95.0,Exiled into the dangerous forest by her wicked...,William Cottrell,David Hand,Wilfred Jackson,Larry Morey,Perce Pearce,196361,184.93,1930

In [86]:
#Les films avec une note > 8 et un revenu > 100
df[(df['IMDB_Rating'] > 8) & (df['Revenue'] > 100)]

,Title,Released Year,Duration Min,Genre,IMDB_Rating,Meta Score,Movie_Details,Director,Main Actor 1,Main Actor 2,Main Actor 3,Main Actor 4,Num_Vote,Revenue,Decade
1,The Godfather,1972,175,"Crime, Drama",9.2,100.0,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1798731,134.97,1970
2,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,84.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2574810,534.86,2000
3,The Lord of the Rings: The Return of the King,2003,201,"Action, Adventure, Drama",9.0,94.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1787701,377.85,2000
8,Pulp Fiction,1994,154,"Crime, Drama",8.9,94.0,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1995346,107.93,1990
9,Inception,2010,148,"Action, Adventure, Sci-Fi",8.8,74.0,A thief who steals corporate secrets through t...,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2284252,292.58,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,Platoon,1986,120,"Drama, War",8.1,92.0,"Chris Taylor, a neophyte recruit in Vietnam, f...",Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,Keith David,408735,138.53,1980
291,Rocky,1976,120,"Drama, Sport",8.1,70.0,A small-time Philadelphia boxer gets a supreme...,John G. Avildsen,Sylvester Stallone,Talia Shire,Burt Young,Carl Weathers,563395,117.24,1970
295,Jaws,1975,124,"Adventure, Thriller",8.1,87.0,When a killer shark unleashes chaos on a beach...,Steven Spielberg,Roy Scheider,Robert Shaw,Richard Dreyfuss,Lorraine Gary,587696,260.00,1970
298,The Exorcist,1973,122,Horror,8.1,81.0,When a 12-year-old girl is possessed by a myst...,William Friedkin,Ellen Burstyn,Max von Sydow,Linda Blair,Lee J. Cobb,395364,232.91,1970
302,The Sound of Music,1965,172,"Biography, Drama, Family",8.1,63.0,A young novitiate is sent by her convent in 19...,Robert Wise,Julie Andrews,Christopher Plummer,Eleanor Parker,Richard Haydn,228758,163.21,1960

In [87]:
# KPI1 : Note IMDB Moyenne Globale 
df['IMDB_Rating'].mean()

np.float64(7.9601999999999995)

In [88]:
# KPI2 : Revenu moyen par film 
df['Revenue'].mean()

np.float64(61.836549999999995)

In [89]:
# KPI3 : Taux de films bien notés (note >  8) 
len(df[df['IMDB_Rating'] > 8]) / len(df)

0.332

In [90]:
#KPI4 : Taux de film bien Noté par les critiques (metacsore>70)
len(df[df["Meta Score"] >70])/len(df)

0.805